[[redirects]]
  from = "/api/*"
  to = "http://190.223.58.252:6000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = ":5000"
  to = "http://190.223.58.252:5000:splat"
  status = 200
  force = true
