import create from 'zustand';
import logo from '../assets/LOGO_SAI.png';
import barcode from '../assets/barcode.png';
import qr from '../assets/qr.png';

const useStore = create((set) => ({
  logo : logo,
  barcode : barcode,
  qr : qr,
  idreceptor: '',
  firstname: '',
  lastname: '',
  phone: '',
  rateKm: 0,
  rateKg: 0,
  additionalCharges: 0,
  transportType: 0,
  km: 0,
  kg: 0,
  size: '',
  cost: 0,
  costwadd: 0,
  origin: null,
  destination: null,
  originAddress: '',
  destinationAddress: '',
  map: null,
  directionsDisplay: null,
  distance: 0,
  duration: 0,
  length: 8,
  width: 11,
  height: 4,
  weight: 0,
  setIdReceptor: (idreceptor) => set({ idreceptor }),
  setFirstname: (firstname) => set({ firstname }),
  setLastname: (lastname) => set({ lastname }),
  setPhone: (phone) => set({ phone }),
  setRateKm: (rateKm) => set({ rateKm }),
  setRateKg: (rateKg) => set({ rateKg }),
  setAdditionalCharges: (additionalCharges) => set({ additionalCharges }),
  setTransportType: (transportType) => set({ transportType }),
  setKm: (km) => set({ km }),
  setKg: (kg) => set({ kg }),
  setSize: (size) => set({ size }),
  setCost: (cost) => set({ cost }),
  setCostwadd: (costwadd) => set({ costwadd }),
  setOrigin: (origin) => set({ origin }),
  setDestination: (destination) => set({ destination }),
  setOriginAddress: (originAddress) => set(() => ({ originAddress })),
  setDestinationAddress: (destinationAddress) => set(() => ({ destinationAddress })),
  setDirectionsDisplay: (directionsDisplay) => set(() => ({ directionsDisplay })),
  setDistance: (distance) => set(() => ({ distance })),
  setMap: (map) => set({ map }),
  setDuration: (duration) => set({ duration }),
  setLength: (length) => set({ length }),
  setWidth: (width) => set({ width }),
  setHeight: (height) => set({ height }),
  setWeight: (weight) => set({ weight }),
}));

export default useStore;
